#!/usr/bin/env zsh

# This file is only sourced for login shells
# Good place for commands that should run once per login session
# or for setting the PATH from package managers

# Initialize Homebrew
# This adds Homebrew's bin directories to PATH and sets up other Homebrew environment variables
# It's in .zprofile because:
# 1. It only needs to run once per login
# 2. It modifies PATH which should be available to all subshells
eval "$(/opt/homebrew/bin/brew shellenv)"
