#!/usr/bin/env bash

# This file is always sourced, for all shells (login, interactive, non-interactive)
# Best place for environment variables that should be available everywhere

# Set XDG base directory specification
# This defines standard locations for user config files
export XDG_CONFIG_HOME="$HOME/.config"

# Set default editors
# These are used by many programs to determine which editor to open
export EDITOR=vim
export VISUAL=vim

# I only use bash when ghostty or kitty aren't available
export TERM=xterm-256color

# Terminal color settings
# CLICOLOR enables colorized output in macOS Terminal
export CLICOLOR=1
# LS_COLORS defines colors for different file types in ls output
export LS_COLORS='no=00:fi=00:di=00;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:*.xml=00;31:'

# Path modifications
export PATH="~/.atuin/bin:$PATH"
export PATH=~/bin:/usr/local/linkedin/bin:$PATH
hash -r
